export const categoryTitles = {
  thisSeasonPopular: "Popular this season",
  nextSeason: "Upcoming next season",
  movie: "Movie",
  allTimePopular: "All Time Popular",
  topAnime: "Top Anime",
  music: "Music",

  "Miyazaki, Hayao": "Hayao Miyazaki",
  "Kon, Satoshi": "Satoshi Kon",
  "Kawaguchi, Yuichiro": "Yuichiro Kawaguchi",
  "Kawaguchi, Yuichiro": "Yuichiro Kawaguchi",
  "Oshii, Mamoru": "Mamoru Oshii",
  "Otomo, Katsuhiro": "Katsuhiro Otomo",
  "Hosoda, Mamoru": "Mamoru Hosoda",
  "Oshii, Mamoru": "Mamoru Oshii",
  "Otomo, Katsuhiro": "Katsuhiro Otomo",
  "Anno, Hideaki": "Hideaki Anno",
  "Shinkai, Makoto": "Makoto Shinkai",
  "Shinbou, Akiyuki": "Akiyuki Shinbo",
  "Yamada, Naoko": "Naoko Yamada",
  "Yuasa, Masaaki": "Masaaki Yuasa",
  "Watanabe, Shinichirou": "Shinichirou Watanabe",
  "Imaishi, Hiroyuki": "Hiroyuki Imaishi",
};
export const categories = [
  "thisSeasonPopular",
  "Slice of Life",
  "nextSeason",
  "Adventure",
  "Fantasy",
  "Drama",
  "Award Winning",
  "Avant Garde",
  "Action",
  "Sci-Fi",
  "Miyazaki, Hayao",
  "Shinkai, Makoto",
  "allTimePopular",
  "topAnime",
  "Supernatural",
  "Mystery",
  "movie",
  "music",
  "Comedy",
  "Romance",
  "Kon, Satoshi",
  "Anno, Hideaki",
  "Yuasa, Masaaki",
  "Sports",
  "Watanabe, Shinichirou",
  "Shinbou, Akiyuki",
  "Horror",
  "Hosoda, Mamoru",
  "Suspense",
  "Imaishi, Hiroyuki",
  "Yamada, Naoko",
  "Oshii, Mamoru",
  "Gourmet",
];

export const genres = [
  "Fantasy",
  "Sci-Fi",
  "Drama",
  "Comedy",
  "Action",
  "Adventure",
  "Romance",
  "Slice of Life",
  "Supernatural",
  "Mystery",
  "Avant Garde",
  "Sports",
  "Horror",
  "Suspense",
  "Gourmet",
  "Award Winning",
];

export const directors = [
  "Miyazaki, Hayao",
  "Shinkai, Makoto",
  "Kon, Satoshi",
  "Anno, Hideaki",
  "Yuasa, Masaaki",
  "Watanabe, Shinichirou",
  "Shinbou, Akiyuki",
  "Hosoda, Mamoru",
  "Imaishi, Hiroyuki",
  "Yamada, Naoko",
  "Oshii, Mamoru",
];
