export const languages = [
  { name: "English", code: "en" },
  { name: "中文", code: "zh" },
  { name: "Español", code: "es" },
  { name: "Français", code: "fr" },
  { name: "Deutsch", code: "de" },
  { name: "Русский", code: "ru" },
  { name: "日本語", code: "ja" },
  { name: "한국어", code: "ko" },
  { name: "Italiano", code: "it" },
  { name: "Português", code: "pt" },
  { name: "العربية", code: "ar" },
  { name: "हिन्दी", code: "hi" },
  { name: "বাংলা", code: "bn" },
  { name: "Türkçe", code: "tr" },
  { name: "Nederlands", code: "nl" },
  { name: "Polski", code: "pl" },
  { name: "Bahasa Indonesia", code: "id" },
  { name: "Tiếng Việt", code: "vi" },
  { name: "ภาษาไทย", code: "th" },
  { name: "עברית", code: "he" },
];
